country_codes = {
    'Argentina': ['AY', 'AZ', 'L2', 'L3', 'L4', 'L5', 'L6', 'L7', 'L8', 'L9', 'LO', 'LP', 'LQ', 'LR', 'LS', 'LT', 'LU', 'LV', 'LW'],
    'Aruba': ['P4'],
    'Bahamas': ['C6'],
    'Bélice': ['V3, V4'],
    'Bolivia': ['CP'],
    'Bonaire': ['PJ4'],
    'Brazil': ['PP', 'PQ', 'PR', 'PS', 'PT', 'PU', 'PV', 'PW', 'PX', 'PY', 'ZV', 'ZW', 'ZX', 'ZY', 'ZZ'],
    'Chile': ['3G', 'CA', 'CB', 'CC', 'CD', 'CE', 'XQ', 'XR'],
    'Colombia': ['5J', '5K', 'HJ', 'HK'],
    'Curazao': ['PJ2'],
    'Isla de Pascua': ['3GØ', 'CAØ', 'CBØ', 'CCØ', 'CDØ', 'CEØ', 'XQØ', 'XRØ'],
    'Ecuador': ['HC', 'HD'],
    'Islas Malvinas / Falkland Island': ['VP8'],
    'Fernando de Noronha': ['PPØF', 'PQØF', 'PRØF', 'PSØF', 'PTØF', 'PUØF', 'PVØF', 'PWØF', 'PXØF', 'PYØF', 'PYØZ', 'ZVØF', 'ZWØF', 'ZXØF', 'ZYØF', 'ZYØZ', 'ZZØF', 'PPØR', 'PQØR', 'PRØR', 'PSØR', 'PTØR', 'PUØR', 'PVØR', 'PWØR', 'PXØR', 'PYØR', 'ZVØR', 'ZWØR', 'ZXØR', 'ZYØR', 'ZZØR'],
    'Guayana Francesa': ['FY'],
    'Isla Galápagos': ['HC8', 'HD8'],
    'Guyana': ['8R'],
    'Isla Juán Fernández': ['3GØZ', 'CAØZ', 'CBØZ', 'CCØZ', 'CDØZ', 'CEØI', 'CEØZ', 'XQØZ', 'XRØZ'],
    'Isla Malpelo': ['HJØ', 'HKØ'],
    'Paraguay': ['ZP'],
    'Perú': ['4T', 'OA', 'OB', 'OC'],
    'Isla Peter 1': ['3Y'],
    'San Félix y San Ambrosio': ['3GØX', 'CAØX', 'CBØX', 'CCØ'],
    'Isla Georgia del Sur': ['VP8/G'],
    'Islas Orcadas del Sur': ['VP8/O'],
    'Sandwich del Sur': ['VP8/S'],
    'Islas Shetland del Sur': ['VP8/H'],
    'St. Pedro y San Pablo': ['PPØS', 'PQØS', 'PRØS', 'PSØS', 'PTØS', 'PUØS', 'PVØS', 'PWØS', 'PXØS', 'PYØS', 'ZVØS', 'ZWØS', 'ZXØS', 'ZYØS', 'ZZØS'],
    'Surinam': ['PZ'],
    'Trinidad y Martín Vaz': ['PPØT', 'PQØT', 'PRØT', 'PSØT', 'PTØT', 'PUØT', 'PVØT', 'PWØT', 'PXØT', 'PYØT', 'ZVØT', 'ZWØT', 'ZXØT', 'ZYØT', 'ZZØT'],
    'Uruguay': ['CV','CW','CX'],
    'Venezuela': ['4M','YV','YW','YX','YY'],}

